version: 1.0.{build}-{branch}

environment:
  GENERATOR: "MinGW Makefiles"
  # - GENERATOR: "MSYS Makefiles"
  # matrix:
  #   - BUILD_SHARED_LIBS: "Off"
  #   - BUILD_SHARED_LIBS: "On"

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir _build
  - cd _build

build_script:
  # Test with stricter flags
  - set CFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector -g3 -pedantic -W -Wall -Wbad-function-cast -Wcast-align \
      -Wcast-qual -Wdisabled-optimization -Wendif-labels -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Winline \
      -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unused-parameter -Wpointer-arith -Wshadow \
      -Wstrict-prototypes -Wstack-protector -Wswitch -Wundef -Wwrite-strings"
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DCMAKE_C_FLAGS="%CFLAGS% -DRAPLCAP_LOG_LEVEL=0" ..
  - cmake --build . --config %CONFIGURATION% -- VERBOSE=1
  # - cmake --build . --config %CONFIGURATION%
  # - C:\MinGW\msys\1.0\bin\sh --login -c "
  #     cd /c/projects/raplcap &&
  #     mkdir _build &&
  #     cd _build &&
  #     cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -G'MSYS Makefiles' &&
  #     make
  #     "

artifacts:
  - path: '**\*.a'
  # - path: '**\*.dll'
  - path: '**\rapl-configure-*.exe'
